/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 30-05-2017 16:23:08 				*/
/*  DBMS       : Oracle 						*/
/*  Grammer Checked and Tested        */
/* ---------------------------------------------------- */

/* Drop Tables */

DECLARE
  C NUMBER;
BEGIN
SELECT COUNT(*) INTO C
FROM USER_TABLES
  WHERE TABLE_NAME = 'CASH_SIDE_EMPLOYEES' ;
  IF (C > 0) THEN
    EXECUTE IMMEDIATE 'DROP TABLE CASH_SIDE_EMPLOYEES CASCADE CONSTRAINTS';
END IF;
END;



/* Create Tables */

CREATE TABLE Cash_Side_Employees
(
	Em_ID VARCHAR2(64) NOT NULL,
	em_role varchar2(16) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

create or replace trigger trigger_em_delete
	before delete on cash_side_employees
	for each row

begin 
	update orders set EM_ID= '________' where em_id=:old.em_id;
	update payments set EM_ID= '________' where em_id=:old.em_id;
	update discount_rules set EM_ID= '________' where em_id=:old.em_id;
	update cash_side_employees set em_id='________', em_role='quit' where em_id=:old.em_id;
end trigger_em_delete;


SHOW ERRORS
;

ALTER TABLE Cash_Side_Employees
 ADD CONSTRAINT PK_Cash_Side_Employees
	PRIMARY KEY (Em_ID) USING INDEX
;

desc Cash_Side_Employees

insert into cash_side_employees
(em_id)
values
('________');
