/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 30-05-2017 16:23:08 				*/
/*  DBMS       : Oracle 						*/
/*  Grammer Checked and Tested        */
/* ---------------------------------------------------- */

/* Drop Tables */

DECLARE
  C NUMBER;
BEGIN
SELECT COUNT(*) INTO C
FROM USER_TABLES
  WHERE TABLE_NAME = 'DISCOUNT_RULES' ;
  IF (C > 0) THEN
    EXECUTE IMMEDIATE 'DROP TABLE DISCOUNT_RULES CASCADE CONSTRAINTS';
END IF;
END;



/* Create Tables */

CREATE TABLE Discount_Rules
(
	Rule_UUID CHAR(32) NOT NULL,
	Rule_Type VARCHAR2(50) NOT NULL,
	Em_ID VARCHAR2(64) NOT NULL,
	Rule_Name VARCHAR2(50) NOT NULL,
	Discount_Rate NUMBER(8,2),
	Free_Money NUMBER(8,2),
	SPECIAL_PRICE NUMBER(8,2),
	Condition_Value NUMBER(8,2),
	DATE_PERIOD_START DATE NOT NULL,
	DATE_PERIOD_END DATE NOT NULL,
	DAY_PERIOD_START NUMBER(4) NOT NULL,
	DAY_PERIOD_END NUMBER(4) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

CREATE INDEX PK_Discount_Rules
 ON Discount_Rules (Rule_UUID)
;

ALTER TABLE Discount_Rules
 ADD CONSTRAINT PK_Discount_Rules
	PRIMARY KEY (Rule_UUID) USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE Discount_Rules
 ADD CONSTRAINT FK_Em_Create_Rules
	FOREIGN KEY (Em_ID) REFERENCES Cash_Side_Employees (Em_ID)
;
