/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 30-5ÔÂ-2017 16:23:08 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TABLES
  WHERE TABLE_NAME = 'DISCOUNT_GOODS' ;
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TABLE DISCOUNT_GOODS CASCADE CONSTRAINTS'; 
END IF; 
END; 



/* Create Tables */

CREATE TABLE Discount_Goods
(
	Rule_UUID CHAR(32) NOT NULL,
	Good_ID VARCHAR2(64) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

CREATE INDEX IXFK_Discount_Goo_Discoun01 
 ON Discount_Goods(Rule_UUID) 
;

ALTER TABLE Discount_Goods
 ADD CONSTRAINT PK_Discount_Goods
	PRIMARY KEY (Rule_UUID,Good_ID) USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE Discount_Goods
 ADD CONSTRAINT FK_Rules_have_Goods
	FOREIGN KEY (Rule_UUID) REFERENCES Discount_Rules (Rule_UUID)
;