/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 30-5ÔÂ-2017 16:23:08 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TABLES
  WHERE TABLE_NAME = 'PAYMENTS' ;
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TABLE Payments CASCADE CONSTRAINTS'; 
END IF; 
END; 



/* Create Tables */

CREATE TABLE Payments
(
	Payment_ID CHAR(32) NOT NULL,
	Payment_Sum NUMBER(16,2) NOT NULL,
	PAYMENT_CHANNELSIDE_ID VARCHAR2(64) NOT NULL,
	Payment_Channel VARCHAR2(64) NOT NULL,
	EM_ID VARCHAR2(64) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

create or replace trigger trigger_payment_id
  before insert on payments 
  for each row
declare
  nextid payments.Payment_ID%TYPE;
begin
  IF :new.payment_id IS NULL or :new.payment_id='00000000000000000000000000000000' THEN 
    select 
	to_char(sysdate,'YYYYMMDDHH24MISS')||to_char(seq_payment.nextval,'fm000000000000000000') 
	into nextid
	from dual;
    :new.payment_id:=nextid;
  end if;
end trigger_payment_id;


SHOW ERRORS 


ALTER TABLE Payments
 ADD CONSTRAINT PK_Payments
	PRIMARY KEY (Payment_ID) USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE Payments 
 ADD CONSTRAINT FK_Em_Responsible_Payments
	FOREIGN KEY (EM_ID) REFERENCES Cash_Side_Employees (Em_ID)
;