/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 30-5ÔÂ-2017 16:23:08 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */
DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TABLES
  WHERE TABLE_NAME = 'ORDERS' ;
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS'; 
END IF; 
END; 


/* Create Tables */

CREATE TABLE Orders
(
	Order_ID CHAR(32) NOT NULL,
	Order_Sum NUMBER(8,2) NOT NULL,
	Sum_Money NUMBER(10,2) NOT NULL,
	Order_Cus_ID VARCHAR2(50),
	Order_Status VARCHAR2(50) NOT NULL,
	Payment_ID CHAR(32),
	EM_ID VARCHAR2(64) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

CREATE INDEX IXFK_Payment_has_Orders_P01  
 ON Orders(Payment_ID) 
;

CREATE INDEX PK_Orders   
 ON Orders(Order_ID) 
;

ALTER TABLE orders
 ADD CONSTRAINT PK_Orders
	PRIMARY KEY (Order_id) USING INDEX
;


create or replace trigger trigger_order_id_seq
  before insert on orders  
  for each row
declare
  nextid orders.Order_ID%TYPE;
begin
  IF :new.Order_ID IS NULL or :new.Order_ID='00000000000000000000000000000000' THEN 
    select 
	to_char(sysdate,'YYYYMMDDHH24MISS')||to_char(seq_order.nextval,'fm000000000000000000') 
	into nextid
	from dual;
    :new.Order_ID:=nextid;
  end if;
end trigger_order_id_seq;

SHOW ERRORS 
;

/* Create Foreign Key Constraints */

ALTER TABLE Orders
 ADD CONSTRAINT FK_Em_Responsible_Orders
	FOREIGN KEY (EM_ID) REFERENCES Cash_Side_Employees (Em_ID)
;

ALTER TABLE Orders
 ADD CONSTRAINT FK_Payment_has_Orders
	FOREIGN KEY (Payment_ID) REFERENCES Payments (Payment_ID)
;