/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 30-5ÔÂ-2017 16:23:08 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TABLES
  WHERE TABLE_NAME = 'PRESENTS' ;
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TABLE PRESENTS CASCADE CONSTRAINTS'; 
END IF; 
END; 

/* Create Tables */

CREATE TABLE Presents
(
	Present_UUID CHAR(32) NOT NULL,
	Present_Type VARCHAR2(64) NOT NULL,
	Present_Condition_Value NUMBER(8,2),
	Present_Discount_Value NUMBER(8,2),
	Rule_UUID CHAR(32) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

CREATE INDEX IXFK_Rule_has_many_Presen01  
 ON Presents (Rule_UUID) 
;

ALTER TABLE Presents
 ADD CONSTRAINT PK_Presents
	PRIMARY KEY (Present_UUID) USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE Presents 
 ADD CONSTRAINT FK_Rule_has_many_Presents
	FOREIGN KEY (Rule_UUID) REFERENCES Discount_Rules (Rule_UUID)
;